"""
01/30/2020
This program  prompts the user to enter a number and asks if she has another number to enter.
The program calculates statistics for integer data that include total of numbers, smallest of numbers,
largest of numbers, number of even numbers, number of odd numbers, and average of numbers.
"""
#My Program
total=0
smallest=None
condition= True
largest=0
even_number=0
odd_number=0
average=0
total_inputs=0

while condition:
    number= input('Please type a number')
    total += int(number)
    total_inputs+=1
    temp=int(number)
    if smallest:
        if temp<smallest:
            smallest=temp
    else:
        smallest=int(number)
    if largest:
        if temp>largest:
            largest=temp
    else:
        largest=int(number)

    if temp% 2== 0:
        even_number+=1

    else:
        odd_number+=1

    another= input('Do you have another number to enter?')
    if another =='n':
        condition = False

average=total/total_inputs

print("the total sum of inputs", total)
print("the smallest number", smallest)
print("the largest number",largest)
print("the number of even inputs", even_number)
print("the number of odd inputs", odd_number)
print("the average of all inputs", average)


#My Output, this is the actual output generated by the program above.
"""
/Users//PycharmProjects/Assignment3/venv/bin/python /Users//PycharmProjects/lab_assignment_4_Processing_Data/Lab_Assignment_4_Processing_Data.py
Please type a number7
Do you have another number to enter?y
Please type a number-13
Do you have another number to enter?y
Please type a number-3
Do you have another number to enter?y
Please type a number99
Do you have another number to enter?n
the total sum of inputs 90
the smallest number -13
the largest number 99
the number of even inputs 0
the number of odd inputs 4
the average of all inputs 22.5

Process finished with exit code 0

/Users//PycharmProjects/Assignment3/venv/bin/python /Users//PycharmProjects/lab_assignment_4_Processing_Data/Lab_Assignment_4_Processing_Data.py
Please type a number-10
Do you have another number to enter?y
Please type a number-22
Do you have another number to enter?y
Please type a number-6
Do you have another number to enter?y
Please type a number-100
Do you have another number to enter?n
the total sum of inputs -138
the smallest number -100
the largest number -6
the number of even inputs 4
the number of odd inputs 0
the average of all inputs -34.5

Process finished with exit code 0
"""

