"""
02/13/2020
The application program interface (API) is a set of routines, protocols, and tools for building software applications.
The API includes the name of the function, parameter the function that it will accept, what the function does with its
parameter, what value the function returns, and whether the function does any input/output. I wrote the full function
definition for each of the five functions and formatted my output to satisfy the rubric criteria.
"""
# My Program


# This function takes a list, looks at the first & last elements, swaps the first & last elements, and returns a list.
def swapFirstAndLast(myList):
    length = len(myList)
    temp = myList[0]
    myList[0] = myList[length - 1]
    myList[length - 1] = temp


# This function takes a list, shifts each element to the right and placed the last (rightmost) element in the zeroth
# position, and returns a list.
def shiftRight(myList):
    length = len(myList)
    temp = myList[length - 1]
    reverse_counter = length - 1
    for index in range(length):
        myList[reverse_counter] = myList[reverse_counter - 1]
        reverse_counter -= 1
    myList[0] = temp


# This function takes a list, looks at each element, doubles the value of each element, and returns a list.
def double(myList):
    for i in range(len(myList)):
        myList[i] = myList[i]*2


# This function takes a list, looks at the elements, if the elements are sorted in ascending order
# it returns True or returns False otherwise.
def isSorted(myList):
    for i in range(1, len(myList)):
        if myList[i - 1] > myList[i]:
            return False
    return True


# This function takes a list, looks at each element, replaces any even elements with a zero, and returns a list.
def replaceEvens(myList):
    for i, n in enumerate(myList):
        if not n % 2:
            myList[i] = 0


# tests swapFirstAndLast()
myList = [1, 4, 2, 9]
print("RUN for: swapFirstAndLast(myList):")
print(myList)
swapFirstAndLast(myList)
print(myList)
print()

# tests shiftRight()
myList = [1, 4, 2, 9]
print("RUN for: shiftRight(myList):")
print(myList)
shiftRight(myList)
print(myList)
print()

# tests double()
myList = [1, 4, 2, 9]
print("RUN for: double(myList):")
print(myList)
double(myList)
print(myList)
print()

# tests isSorted()
myList = [1, 4, 2, 9]
print("RUN for: isSorted(myList):")
if isSorted(myList):
    print("myList is sorted")
else:
    print("myList is not sorted")
myOtherList = [1, 2, 4, 9]
print()
print("RUN for: isSorted(myOtherList):")
if isSorted(myOtherList):
    print("myOtherList is sorted")
else:
    print("myOtherList is not sorted")
print()

# tests replaceEvens()
myList = [1, 4, 2, 9]
print("RUN for: replaceEvens")
print(myList)
replaceEvens(myList)
print(myList)
print()

# My Output, this is the actual output generated by the program above.
"""
RUN for: swapFirstAndLast(myList):
[1, 4, 2, 9]
[9, 4, 2, 1]

RUN for: shiftRight(myList):
[1, 4, 2, 9]
[9, 1, 4, 2]

RUN for: double(myList):
[1, 4, 2, 9]
[2, 8, 4, 18]

RUN for: isSorted(myList):
myList is not sorted

RUN for: isSorted(myOtherList):
myOtherList is sorted

RUN for: replaceEvens
[1, 4, 2, 9]
[1, 0, 0, 9]

Process finished with exit code 0
"""

