"""
02/23/2020
This program asks the user for a filename, opens the file and reads the file once before reporting back to
the user the number of characters (including spaces and end of line characters), the number of words, and
the number of lines in the file. If the user enters the name of a file that doesn't exist, my program gives her as many
tries as she needs to type a valid filename. I wrote a separate, reusable function called data_filename that repeatedly
asks the user for a filename, until she types in the name of a file that my program is able to open. The reusable function
will then return a string containing the valid filename as its returned value. My program then opens and read the file
with that name. I created a reusable function, read a text file from the disk, and used try/except to avoid crashing.
Also, I have included the external data file (test output) that I used to test my program.
"""
# My Program

def fileread():
    while True:
        data_filename = input('What is the name of the file you would like to process?')
        try:
            data_file = open(data_filename, "r")
            break
        except:
            print("not valid")

    data_file.close()
    return (data_filename)

data_filename = fileread()
lines = 0
characters = 0
words = 0

with open(data_filename) as f:
    for line in f:
        lines += 1
        characters += len(line)
        words += len(line.split())
print("# of lines:", lines)
print("# of characters:", characters)
print("# of words:", words)

# My Output, this is the actual output generated by the program above, including the external data file (test).
"""
What is the name of the file you would like to process?x
not valid
What is the name of the file you would like to process?test
# of lines: 3
# of characters: 70
# of words: 16

I defined a separate function that reads the filename from the user and confirms that the file exists. I confirmed my 
program runs properly. If the filename the user enters doesn't exist, I use try/except blocks to run the program.
My program read through the file just once to compile the three statistics (number of lines, number of characters, and 
number of words). I used the test file name to test my program.

Process finished with exit code 0
"""

