"""
01/23/2020
This program prompts the user to enter three pieces of information value of car, age of driver, and number of traffic tickets.
The program read the responses, calculated, and printed the calculations of the monthly premium that the driver will have to pay for insurance,
if the customer is refused coverage the reason will be stated below the output.
"""
#My Program
import sys
age= 0
tickets= 0
value= 0
total_percent = 0.05

value = int(input ("Enter value:"))
age = int(input ("Enter age:"))
tickets = int(input ("Enter tickets"))
premium = (value * 0.05)

if age < 25:
    premium *= 1.15
elif 25 < age <= 29:
    premium *=1.10

if tickets == 1:
    premium *=1.10
elif tickets == 2:
    premium *=1.25
elif tickets == 3:
    premium *=1.50
elif tickets >3:
    print ("Premium: $0 customer refused coverage due to excessive traffic tickets")
    exit()
else:
    pass

print ("%.2f" % premium)

#My Output, this is the actual output generated by the program above.
"""
/Users//PycharmProjects/Assignment3/venv/bin/python /Users//PycharmProjects/Assignment3/assignment3.py
Enter value:10000
Enter age:35
Enter tickets1
550.00
Based on the driver's responses, the value of the car, age of driver, and number of traffic tickets were calculated,
this driver will have to pay a $550.00 monthly premium for insurance. 

Process finished with exit code 0

/Users//PycharmProjects/Assignment3/venv/bin/python /Users//PycharmProjects/Assignment3/assignment3.py
Enter value:15000
Enter age:29
Enter tickets2
1031.25
Based on the driver's responses, the value of the car, age of driver, and number of traffic tickets were calculated,
this driver will have to pay a $1031.25 monthly premium for insurance.

Process finished with exit code 0

/Users//PycharmProjects/Assignment3/venv/bin/python /Users//PycharmProjects/Assignment3/assignment3.py
Enter value:850
Enter age:19
Enter tickets3
73.31
Based on the driver's responses, the value of the car, age of driver, and number of traffic tickets were calculated,
this driver will have to pay a $73.31 monthly premium for insurance.

Process finished with exit code 0

/Users//PycharmProjects/Assignment3/venv/bin/python /Users//PycharmProjects/Assignment3/assignment3.py
Enter value:12500
Enter age:81
Enter tickets4
Premium: $0 customer refused coverage due to excessive traffic tickets
Based on the driver's responses, the value of the car, age of driver, and number of traffic tickets were calculated,
the driver was refused insurance coverage since the driver has excessive traffic tickets.Drive is a liability to insure. 

Process finished with exit code 0
"""

