"""
03/28/2020

This program calculates the frequency of all the letters (a through z) in a file specified by the user. This program
asks the user for the name of a file, open the file, and read it through once. Then, this program
reports the frequency of each letter of the alphabet, regardless of case (capital or lower case). The
frequency of a letter is defined to be the number of times that letter appears in the file divided by the total number
of letters in the file.
"""
# My Program

import assignment7_2

letters = {}
letters['a'] = 0
letters['b'] = 0
letters['c'] = 0
letters['d'] = 0
letters['e'] = 0
letters['f'] = 0
letters['g'] = 0
letters['h'] = 0
letters['i'] = 0
letters['j'] = 0
letters['k'] = 0
letters['l'] = 0
letters['m'] = 0
letters['n'] = 0
letters['o'] = 0
letters['p'] = 0
letters['q'] = 0
letters['r'] = 0
letters['s'] = 0
letters['t'] = 0
letters['u'] = 0
letters['v'] = 0
letters['w'] = 0
letters['x'] = 0
letters['y'] = 0
letters['z'] = 0
letters[' '] = 0
letters['\n'] = 0
count = 0

data_filename = assignment7_2.fileread()
for lines in data_filename.readlines():
    for elem in lines:
        letters[elem.lower()] += 1
        count += 1
print ('a = ', letters ['a']/count * 100)
print ('b = ', letters ['b']/count * 100)
print ('c = ', letters ['c']/count * 100)
print ('d = ', letters ['d']/count * 100)
print ('e = ', letters ['e']/count * 100)
print ('f = ', letters ['f']/count * 100)
print ('g = ', letters ['g']/count * 100)
print ('h = ', letters ['h']/count * 100)
print ('i = ', letters ['i']/count * 100)
print ('j = ', letters ['j']/count * 100)
print ('k = ', letters ['k']/count * 100)
print ('l = ', letters ['l']/count * 100)
print ('m = ', letters ['m']/count * 100)
print ('n = ', letters ['n']/count * 100)
print ('o = ', letters ['o']/count * 100)
print ('p = ', letters ['p']/count * 100)
print ('q = ', letters ['q']/count * 100)
print ('r = ', letters ['r']/count * 100)
print ('s = ', letters ['s']/count * 100)
print ('t = ', letters ['t']/count * 100)
print ('u = ', letters ['u']/count * 100)
print ('v = ', letters ['v']/count * 100)
print ('w = ', letters ['w']/count * 100)
print ('x = ', letters ['x']/count * 100)
print ('y = ', letters ['y']/count * 100)
print ('z = ', letters ['z']/count * 100)

# My Output, this is the actual output generated by the program above, including the external data file (test.txt).
"""
What is the name of the file you would like to process?test.txt
a =  5.714285714285714
b =  0.0
c =  1.4285714285714286
d =  2.857142857142857
e =  8.571428571428571
f =  2.857142857142857
g =  1.4285714285714286
h =  5.714285714285714
i =  5.714285714285714
j =  0.0
k =  0.0
l =  4.285714285714286
m =  4.285714285714286
n =  4.285714285714286
o =  11.428571428571429
p =  1.4285714285714286
q =  0.0
r =  2.857142857142857
s =  2.857142857142857
t =  10.0
u =  1.4285714285714286
v =  0.0
w =  1.4285714285714286
x =  0.0
y =  0.0
z =  0.0

Also, I imported the function I created for Assignment #7_2 that reads the filename and opens the file. In the above program
I used a dictionary to keep track of the count of each letter of the alphabet. I confirmed the program ran properly
and read through the file just once in order to compile all of the required statistics.

Process finished with exit code 0
"""

